site_name: lernOS Congention 2024
site_url: https://cogneon.github.io/cogneon/loscon24
docs_dir: src
site_dir: docs
edit_uri: ""

nav:
- Startseite: index.md
- Kommunikation: communication.md
- Programm: program.md
- Vorabend: eve.md

theme:
    name: readthedocs
    locale: de
    logo: images/loscon24-badge.png

repo_name: 'cogneon/loscon24'
repo_url: 'https://github.com/cogneon/loscon24'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    generator: false


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search