site_name: lernOS Convention 2024
site_url: https://cogneon.github.io/cogneon/loscon24
docs_dir: src
site_dir: docs
edit_uri: ""

nav:
- Startseite: index.md
- Kommunikation: communication.md
- Vorab-Webkonferenz: pre-call.md
- Merch: merch.md
- Mitbringen: to-bring.md
- Anreise: getting-there.md
- Vorabend: eve.md
- Lokation: location.md
- Dezentrale Lokationen: loscon-everywhere.md
- Programm: program.md
- Abendprogramm: party.md
- Barrierefreiheit: accessibility.md
- Badge: badge.md
- Archiv: archive.md
- FAQ: faq.md
- Toolset:
  - Netzwerk: network.md
  - Discord: discord.md
  - Hybrid Meeting Kit: hmk.md
- Orga:
  - Orga-Team: orga-team.md
  - Design: design.md
  - Infoseiten bearbeiten: infopages.md
  - Auf-/Abbau: logistics.md

theme:
    name: readthedocs
    locale: de
    logo: img/loscon24-badge.png

repo_name: 'cogneon/loscon24'
repo_url: 'https://github.com/cogneon/loscon24'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    generator: false


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search