site_name: Infoseiten zur lernOS Convention 2024 (2.-3. Juli 2024)
site_name: lernOS Convention 2024
site_url: https://cogneon.github.io/cogneon/loscon24
docs_dir: src
site_dir: docs
edit_uri: ""

repo_name: 'cogneon/loscon24'
repo_url: 'https://github.com/cogneon/loscon24'


nav:
- Startseite: index.md
- Kommunikation: communication.md
- FAQ: faq.md
- Vorbereitung:
  - Vorab-Webkonferenz: pre-call.md
  - Merch: merch.md
  - Mitbringen: to-bring.md
  - Anreise: getting-there.md
  - Vorabend: eve.md
- Veranstaltungsort:
  - Die Burg: location.md
  - Dezentrale Lokationen: loscon-everywhere.md
  - Barrierefreiheit: accessibility.md
- Programm:
  - Programm: program.md
  - Abendprogramm: party.md
  - Archiv: archive.md
- Toolset:
  - Netzwerk: network.md
  - Discord: discord.md
  - Hybrid Meeting Kit: hmk.md
- Orga:
  - Orga-Team: orga-team.md
  - Design: design.md
  - Infoseiten bearbeiten: infopages.md
  - Auf-/Abbau: logistics.md
  - Badge: badge.md

theme:
    name: readthedocs
    locale: de
    logo: img/loscon24-badge.png

copyright: Creative Commons Namensnennung 4.0 International (CC BY)

extra_css:
  - loscon24.css

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true


markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - rss